const fs = require('fs');

let content = fs.readFileSync('app.js', 'utf8');

// Find the start and end of the templates object
const startIndex = content.indexOf('const templates = {');
let openBrackets = 0;
let endIndex = -1;
for (let i = startIndex + 18; i < content.length; i++) {
    if (content[i] === '{') openBrackets++;
    else if (content[i] === '}') {
        openBrackets--;
        if (openBrackets === 0) {
            endIndex = i + 1;
            break;
        }
    }
}

let templatesStr = content.substring(startIndex, endIndex);

// We'll evaluate it safely
let templatesObj;
eval(templatesStr.replace('const templates', 'templatesObj'));

// Now for each template, we generate cleanCode
for (let key in templatesObj) {
    let raw = templatesObj[key].code;
    let clean = raw.split('\n').map(line => {
        // Remove comments
        if (line.trim().startsWith('//') && line.match(/(Compare|Visual|Log|Shift|Move|Perform|Mark)/i)) return null;
        
        // Remove void macros
        line = line.replace(/\s*(focus_pointer|focus_array|focus_node|focus_cell|update_next|visit|resolve|record_comparison)\([^;]*\);/g, '');
        
        // Remove compare in while loops
        line = line.replace(/\s*&&\s*compare\([^)]+\)/g, '');
        
        if (line.trim() === '') return null; // remove empty lines generated by macro stripping
        return line;
    }).filter(l => l !== null).join('\n');
    
    // Some lines might be empty originally, we don't want to break formatting too much. 
    // The filter above might remove legit empty lines, but that's okay for clean code.
    templatesObj[key].cleanCode = clean;
}

// Now write it back
let newTemplatesStr = 'const templates = ' + JSON.stringify(templatesObj, null, 4) + ';';

content = content.substring(0, startIndex) + newTemplatesStr + content.substring(endIndex + 1);
fs.writeFileSync('app.js', content);
console.log("Templates cleaned!");
